#!/usr/bin/python
# -*- coding: utf-8 -*-
'''
@date: 2011-11-16
@author: shell.xu
'''
import os, sys, getopt
import segment

dbname = 'frq.db'

def create(filepath):
    ddb = segment.dictdb()
    ddb.loadtxt(filepath)
    ddb.savefile(dbname)

def importdb(filepath):
    ddb = segment.dictdb(dbname)
    ddb.loadtxt(filepath)
    ddb.sync()

def exportdb(filepath):
    ddb = segment.dictdb(dbname)
    with open(filepath, 'w') as fo: ddb.exporttxt(fo)

def adddb(word, frq):
    ddb = segment.dictdb(dbname)
    ddb.add(word.decode('utf-8'), float(frq))
    ddb.sync()

def removedb(word):
    ddb = segment.dictdb(dbname)
    ddb.remove(word.decode('utf-8'))
    ddb.sync()

def lookupdb(word):
    ddb = segment.dictdb(dbname)
    print word, ddb[word.decode('utf-8')]

def statdb():
    ddb = segment.dictdb(dbname)
    print 'count:', ddb.count()
    print 'sumvalue:', ddb.sumvalue()
    print 'avgvalue:', ddb.sumvalue() / ddb.count()
    print 'maxvalue:', ddb.maxvalue()

def waterlevel(wl):
    ddb = segment.dictdb(dbname)
    print ddb.waterlevel(float(wl))

def reducedb(factor):
    ddb = segment.dictdb(dbname)
    ddb.reduce(float(factor))
    ddb.sync()

def shrinkdb(threshold):
    ddb = segment.dictdb(dbname)
    ddb.shrink(float(threshold))
    ddb.sync()

def trans_cedict(infile, outfile):
    words = set()
    with open(infile, 'r') as fi:
        for line in fi:
            if line.startswith('#'): continue
            word = line.split()[1].decode('utf-8')
            if len(word) > 1: words.add(word)
    with open(outfile, 'w') as fo:
        for word in list(words):
            fo.write((u'%s 1\n' % word).encode('utf-8'))

def trans_plain(infile, outfile):
    words = set()
    with open(infile, 'r') as fi:
        for line in fi:
            if line.startswith('#'): continue
            word = line.decode('utf-8').strip()
            if len(word) > 1: words.add(word)
    with open(outfile, 'w') as fo:
        for word in list(words):
            fo.write((u'%s 1\n' % word).encode('utf-8'))

def main():
    opts, args = getopt.getopt(sys.argv[1:], 'd:')
    for opt, val in opts:
        if opt == '-d':
            global dbname
            dbname = val
    funcs = ['create', 'import', 'export', 'add', 'remove', 'lookup',
             'stat', 'waterlevel', 'reduce', 'shrink',
             'trans_cedict', 'trans_plain']
    if len(args) == 0:
        print '%s [%s] .. filename' % (sys.argv[0], '|'.join(funcs))
    elif args[0] == 'create': create(args[1])
    elif args[0] == 'import': importdb(args[1])
    elif args[0] == 'export': exportdb(args[1])
    elif args[0] == 'add': adddb(args[1], args[2])
    elif args[0] == 'remove': removedb(args[1])
    elif args[0] == 'lookup': lookup(args[1])
    elif args[0] == 'stat': statdb()
    elif args[0] == 'waterlevel': waterlevel(args[1])
    elif args[0] == 'reduce': reducedb(args[1])
    elif args[0] == 'shrink': shrinkdb(args[1])
    elif args[0] == 'trans_cedict': trans_cedict(args[1], args[2])
    elif args[0] == 'trans_plain': trans_plain(args[1], args[2])

if __name__ == '__main__': main()
