#!/usr/bin/python
# -*- coding: utf-8 -*-
'''
@date: 2011-11-16
@author: shell.xu
'''
import os, sys, getopt
import segment

dbname = 'frq.db'

def create(filepath):
    ddb = segment.dictdb()
    ddb.loadtxt(filepath)
    ddb.savefile(dbname)

def importdb(filepath):
    ddb = segment.dictdb(dbname)
    ddb.loadtxt(filepath)
    ddb.sync()

def exportdb(filepath):
    ddb = segment.dictdb(dbname)
    with open(filepath, 'w') as fo: ddb.exporttxt(fo)

def adddb(word, frq):
    ddb = segment.dictdb(dbname)
    ddb.add(word.decode('utf-8'), float(frq))
    ddb.sync()

def removedb(word):
    ddb = segment.dictdb(dbname)
    ddb.remove(word.decode('utf-8'))
    ddb.sync()

def lookupdb(word):
    ddb = segment.dictdb(dbname)
    print word, ddb[word.decode('utf-8')]

def statdb():
    ddb = segment.dictdb(dbname)
    count, sumval = len(ddb.values()), sum(ddb.values())
    print 'count: %f\nsumvalue: %f' % (count, sumval)
    print 'avgvalue: %f\nmaxvalue: %f' % (sumval / count, max(ddb.values()))

def waterlevel(wl):
    ddb = segment.dictdb(dbname)
    print ddb.waterlevel(float(wl))

def reducedb(factor):
    ddb = segment.dictdb(dbname)
    ddb.reduce(float(factor))
    ddb.sync()

def shrinkdb(threshold):
    ddb = segment.dictdb(dbname)
    ddb.shrink(float(threshold))
    ddb.sync()

def trans_cedict(infile, outfile):
    words = set()
    with open(infile, 'r') as fi:
        for line in fi:
            if line.startswith('#'): continue
            word = line.split()[1].decode('utf-8')
            if len(word) > 1: words.add(word)
    with open(outfile, 'w') as fo:
        for word in list(words):
            fo.write((u'%s 1\n' % word).encode('utf-8'))

def trans_plain(infile, outfile):
    words = set()
    with open(infile, 'r') as fi:
        for line in fi:
            if line.startswith('#'): continue
            word = line.decode('utf-8').strip()
            if len(word) > 1: words.add(word)
    with open(outfile, 'w') as fo:
        for word in list(words):
            fo.write((u'%s 1\n' % word).encode('utf-8'))

def main():
    opts, args = getopt.getopt(sys.argv[1:], 'd:')
    for opt, val in opts:
        if opt == '-d':
            global dbname
            dbname = val
    funcs = ['create', 'importdb', 'exportdb', 'adddb', 'removedb',
             'lookup', 'statdb', 'waterlevel', 'reducedb', 'shrinkdb',
             'trans_cedict', 'trans_plain']
    if len(args) == 0:
        print '%s cmds params ...' % sys.argv[0]
        for name in cmds: print '%s:%s' % (name, eval(name).__doc__)
    else: eval(args[0])(*args[1:])

if __name__ == '__main__': main()
